current:
  env : test
host:
  test : "https://test.tengmoney.com"
  dev : "https://dev.xx.com"
  uat : "https://uat.xx.com"
  prod: "https://www.xx.com"
corp:
  test:
    #企业简称
    corpName: xx
    corpId: xx
app:
    h5poster:
      corpId: xx
      appId: xx
      appName: xx
      agentId: xx
      componentAppid: xx
staff:
  test:
    staffName: xx
    userId: xx
    staffId: xx
product:
  test:
    productType: xx
    productName: xx
    productId: xx
morning:
  test:
    paperId: xx